//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.13 at 08:16:58 PM AEST 
//


package com.test.gcd.soap.webservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test.gcd.soap.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GcdSumRequest_QNAME = new QName("http://com/test/gcd/soap/WebService", "gcdSumRequest");
    private final static QName _GcdRequest_QNAME = new QName("http://com/test/gcd/soap/WebService", "gcdRequest");
    private final static QName _GcdListRequest_QNAME = new QName("http://com/test/gcd/soap/WebService", "gcdListRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test.gcd.soap.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GcdSumResponse }
     * 
     */
    public GcdSumResponse createGcdSumResponse() {
        return new GcdSumResponse();
    }

    /**
     * Create an instance of {@link GcdListResponse }
     * 
     */
    public GcdListResponse createGcdListResponse() {
        return new GcdListResponse();
    }

    /**
     * Create an instance of {@link GcdResponse }
     * 
     */
    public GcdResponse createGcdResponse() {
        return new GcdResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com/test/gcd/soap/WebService", name = "gcdSumRequest")
    public JAXBElement<Object> createGcdSumRequest(Object value) {
        return new JAXBElement<Object>(_GcdSumRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com/test/gcd/soap/WebService", name = "gcdRequest")
    public JAXBElement<Object> createGcdRequest(Object value) {
        return new JAXBElement<Object>(_GcdRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com/test/gcd/soap/WebService", name = "gcdListRequest")
    public JAXBElement<Object> createGcdListRequest(Object value) {
        return new JAXBElement<Object>(_GcdListRequest_QNAME, Object.class, null, value);
    }

}
