//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.13 at 08:16:58 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/test/gcd/soap/WebService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.test.gcd.soap.webservice;
